#
# Copyright (c) 2019-2020 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

branches:
  except:
    - gh-pages

matrix:
  fast_finish: true

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
  - powershell ". .\tools\build_windows.ps1"
  
environment:
  global:
    B2_CI_VERSION: 1
    B2_CXXFLAGS: -permissive-
    B2_VARIANT: release,debug
    B2_CXXSTD: 11,14,17
  matrix:
    # CMake
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_BUILD_TYPE: Debug
      PLATFORM: x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_BUILD_TYPE: Release
      PLATFORM: x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_BUILD_TYPE: Debug
      PLATFORM: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_BUILD_TYPE: Release
      PLATFORM: x86
    # Boost.Build
    - FLAVOR: Visual Studio 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PLATFORM: x86
      B2_TOOLSET: msvc-14.2
      B2_CXXSTD: 11,14 # Hitting an internal compiler error under C++17 x86, can't reproduce locally 
    - FLAVOR: Visual Studio 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PLATFORM: x64
      B2_TOOLSET: msvc-14.2
